# Generated by Django 2.0.2 on 2018-03-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180213_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单信息', 'verbose_name_plural': '订单信息'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': '购物车喵', 'verbose_name_plural': '购物车喵'},
        ),
    ]
