# Generated by Django 2.2.2 on 2019-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trade', '0003_auto_20180304_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_type',
            field=models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信')], default='alipay', max_length=10, verbose_name='支付类型'),
        ),
    ]
