# Generated by Django 2.0.2 on 2018-03-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '短信验证', 'verbose_name_plural': '短信验证'},
        ),
    ]
