# Generated by Django 2.0.2 on 2018-03-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20180309_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, help_text='电话号码', max_length=11, null=True, verbose_name='电话'),
        ),
    ]
