# Generated by Django 2.0.2 on 2018-03-11 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_operation', '0003_auto_20180311_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='area',
            new_name='district',
        ),
    ]
