# Generated by Django 3.0 on 2020-08-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xadmin_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifyRecord',
            new_name='TyAdminEmailVerifyRecord',
        ),
        migrations.RenameModel(
            old_name='SysLog',
            new_name='TyAdminSysLog',
        ),
    ]
